-- SnapClass database schema for Supabase.
-- Run this file in Supabase Dashboard > SQL Editor.

create table if not exists public.teachers (
    teacher_id bigint generated by default as identity primary key,
    username text not null unique,
    password text not null,
    name text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.students (
    student_id bigint generated by default as identity primary key,
    name text not null,
    face_embedding double precision[],
    voice_embedding double precision[],
    created_at timestamptz not null default now()
);

create table if not exists public.subjects (
    subject_id bigint generated by default as identity primary key,
    subject_code text not null unique,
    name text not null,
    section text not null,
    teacher_id bigint not null references public.teachers(teacher_id) on delete cascade,
    created_at timestamptz not null default now()
);

create table if not exists public.subject_students (
    subject_id bigint not null references public.subjects(subject_id) on delete cascade,
    student_id bigint not null references public.students(student_id) on delete cascade,
    enrolled_at timestamptz not null default now(),
    primary key (subject_id, student_id)
);

create table if not exists public.attendance_logs (
    attendance_id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(student_id) on delete cascade,
    subject_id bigint not null references public.subjects(subject_id) on delete cascade,
    "timestamp" timestamptz not null default now(),
    is_present boolean not null default false
);



create table if not exists public.leave_requests (
    leave_id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(student_id) on delete cascade,
    subject_id bigint not null references public.subjects(subject_id) on delete cascade,
    start_date date not null,
    end_date date not null,
    reason text not null,
    status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
    teacher_note text,
    requested_at timestamptz not null default now(),
    reviewed_at timestamptz
);

create index if not exists subjects_teacher_id_idx on public.subjects(teacher_id);
create index if not exists subject_students_student_id_idx on public.subject_students(student_id);
create index if not exists attendance_logs_student_id_idx on public.attendance_logs(student_id);
create index if not exists attendance_logs_subject_id_idx on public.attendance_logs(subject_id);
create index if not exists leave_requests_student_id_idx on public.leave_requests(student_id);
create index if not exists leave_requests_subject_id_idx on public.leave_requests(subject_id);
create index if not exists leave_requests_status_idx on public.leave_requests(status);

-- The current app performs its own login and accesses Supabase with the anon
-- key, so these prototype policies allow its required reads and writes.
alter table public.teachers enable row level security;
alter table public.students enable row level security;
alter table public.subjects enable row level security;
alter table public.subject_students enable row level security;
alter table public.attendance_logs enable row level security;
alter table public.leave_requests enable row level security;

drop policy if exists "snapclass anon access" on public.teachers;
create policy "snapclass anon access" on public.teachers
    for all to anon using (true) with check (true);

drop policy if exists "snapclass anon access" on public.students;
create policy "snapclass anon access" on public.students
    for all to anon using (true) with check (true);

drop policy if exists "snapclass anon access" on public.subjects;
create policy "snapclass anon access" on public.subjects
    for all to anon using (true) with check (true);

drop policy if exists "snapclass anon access" on public.subject_students;
create policy "snapclass anon access" on public.subject_students
    for all to anon using (true) with check (true);

drop policy if exists "snapclass anon access" on public.attendance_logs;
create policy "snapclass anon access" on public.attendance_logs
    for all to anon using (true) with check (true);

drop policy if exists "snapclass anon access" on public.leave_requests;
create policy "snapclass anon access" on public.leave_requests
    for all to anon using (true) with check (true);

grant usage on schema public to anon;
grant select, insert, update, delete on all tables in schema public to anon;
grant usage, select on all sequences in schema public to anon;
