[theme]
base = "light"
primaryColor = "#b52369"
backgroundColor = "#dff3ff"
secondaryBackgroundColor = "#f2c8dd"
textColor = "#18324a"
font = "sans serif"

[server]
runOnSave = false
fileWatcherType = "none"
enableStaticServing = true
headless = true
maxUploadSize = 50